name: FreezeHost 续期

on:
  workflow_dispatch:
    inputs:
      token_number:
        description: '选择 Token 编号'
        required: true
        default: '1'
        type: choice
        options:
          - '1'
          - '2'
          - '3'
          - '4'
          - '5'

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - name: 测试
        run: echo "工作流显示正常"
